// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    scheduled_payments_contract
    (
        init => init
        createStream => create_stream
        claim => claim
        cancelStream => cancel_stream
        getStream => streams
        getLastStreamId => last_stream_id
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
