// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    scheduled_payments_contract
    (
        init => init
        createSubscription => create_subscription
        triggerPayment => trigger_payment
        cancelSubscription => cancel_subscription
        getSubscription => subscriptions
        getLastId => last_id
        getClientSubscriptions => get_client_subscriptions
        getVendorSubscriptions => get_vendor_subscriptions
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
