// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct SubscriptionContractProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for SubscriptionContractProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = SubscriptionContractProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        SubscriptionContractProxyMethods { wrapped_tx: tx }
    }
}

pub struct SubscriptionContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> SubscriptionContractProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> SubscriptionContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn create_subscription<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<BigUint<Env::Api>>,
        Arg2: ProxyArg<u64>,
    >(
        self,
        vendor: Arg0,
        amount_per_cycle: Arg1,
        frequency: Arg2,
    ) -> TxTypedCall<Env, From, To, (), Gas, u64> {
        self.wrapped_tx
            .raw_call("createSubscription")
            .argument(&vendor)
            .argument(&amount_per_cycle)
            .argument(&frequency)
            .original_result()
    }

    pub fn trigger_payment<
        Arg0: ProxyArg<u64>,
    >(
        self,
        sub_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("triggerPayment")
            .argument(&sub_id)
            .original_result()
    }

    pub fn cancel_subscription<
        Arg0: ProxyArg<u64>,
    >(
        self,
        sub_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("cancelSubscription")
            .argument(&sub_id)
            .original_result()
    }

    pub fn subscriptions<
        Arg0: ProxyArg<u64>,
    >(
        self,
        id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, Subscription<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getSubscription")
            .argument(&id)
            .original_result()
    }

    pub fn last_id(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getLastId")
            .original_result()
    }

    pub fn get_client_subscriptions<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, u64>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getClientSubscriptions")
            .argument(&address)
            .original_result()
    }

    pub fn get_vendor_subscriptions<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, u64>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getVendorSubscriptions")
            .argument(&address)
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone, PartialEq)]
pub struct Subscription<Api>
where
    Api: ManagedTypeApi,
{
    pub client: ManagedAddress<Api>,
    pub vendor: ManagedAddress<Api>,
    pub token_identifier: TokenIdentifier<Api>,
    pub amount_per_cycle: BigUint<Api>,
    pub frequency: u64,
    pub remaining_balance: BigUint<Api>,
    pub last_payment_time: u64,
    pub start_time: u64,
}
